#!/usr/bin/env python3
"""
CO_ Network — emit the PUBLIC-SAFE local data snapshot for the Next.js app.
===========================================================================
Bridges the gap until the Supabase project exists: the web app's data layer
(web/src/lib/data/local.ts) reads these JSON files server-side. IDs and slugs
are generated by the SAME code as scripts/migrate_to_supabase.py, so every
URL minted now survives the Supabase cutover unchanged.

PUBLIC-SAFE ONLY — this snapshot mirrors what RLS exposes to anon users:
directory basics. It must NEVER include contact names, risk flags, provenance
rows, review pain-points, or internal confidence scores (those are owner/admin
scoped and arrive only with real auth + RLS).

Usage:  python scripts/emit_local_snapshot.py
Output: web/src/data/{businesses,categories,neighborhoods}.json
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from migrate_to_supabase import (  # noqa: E402
    build_payloads, load_pre_flatten_membership, parse_rows,
)

OUT = ROOT / "web" / "src" / "data"

PUBLIC_FIELDS = [
    "id", "slug", "name", "category_slug", "category_secondary",
    "neighborhood_label", "address", "postcode", "phone", "website",
    "price_tier", "price_tier_inferred", "rating", "review_count",
    "chamber_member", "status", "location_precision",
]


def main():
    rows = parse_rows()
    old = load_pre_flatten_membership()
    cats, nbhs, businesses, _privates, _fields, _risks, stats = build_payloads(rows, old)

    pub = []
    for b in businesses:
        rec = {k: b.get(k) for k in PUBLIC_FIELDS}
        # location as plain lat/lon (snapshot has no PostGIS)
        loc = b.get("location")
        if loc:  # "SRID=4326;POINT(lon lat)"
            lon, lat = loc.split("POINT(")[1].rstrip(")").split(" ")
            rec["lat"], rec["lon"] = float(lat), float(lon)
        else:
            rec["lat"] = rec["lon"] = None
        pub.append(rec)

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "businesses.json").write_text(
        json.dumps(pub, separators=(",", ":")), encoding="utf-8")
    (OUT / "categories.json").write_text(json.dumps(
        [{"slug": s, "label": l, "high_value": hv} for s, (l, hv) in sorted(cats.items())],
        indent=1), encoding="utf-8")
    (OUT / "neighborhoods.json").write_text(json.dumps(
        [{"label": l, "is_catchall": c} for l, c in sorted(nbhs.items())],
        indent=1), encoding="utf-8")

    print(f"wrote {len(pub)} businesses, {len(cats)} categories, "
          f"{len(nbhs)} neighborhoods -> {OUT}")
    print("membership:", {k: v for k, v in stats.items() if k.startswith('member_')})


if __name__ == "__main__":
    main()
